
POST http://localhost:8080/api/submit
Content-Type: application/json

{
	"first_name":"Yusuf",
	"last_name":"Akinleye",
	"email":"ayaaakinleye@gmail.com",
	"interest":"Adventure"
}


POST http://localhost:8000/login
Content-Type: application/json
